<TurismoCamiriScreen>
    name: 'turismo_camiri'
    md_bg_color: 0.2, 0.2, 0.2, 1

    MDBoxLayout:
        orientation: 'vertical'
        padding: '50dp'
        spacing: '20dp'

        MDLabel:
            text: 'Lugares Turísticos'
            halign: 'center'
            font_style: 'H5'

        MDFillRoundFlatButton:
            text: 'Volver al inicio'
            pos_hint: {'center_x': .5}
            on_release:
                app.root.current = 'home'